# -*- coding: utf-8 -*-
"""Homework01.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1HBmR8MDjWY5OjtUO3FfhpyykN9Mnlu97
"""

# 1. Write a program to use the loop to find the factorial of a given number.
n = int(input())
j =  1
for i in range(1,n+1,1):
  j = j*i
print("factorial of a given number:",j)

# 2. Write a program to print the following start pattern using the loop.
count = 0
for i in range(1,10):
  if i <= 5:
    count +=1
  else:
    count -=1
  for j in range(1,count+1):
    print("*", end=' ')
    
  print('')

#2. or from user input
n = int(input())
for i in range(1,n+1):
  for j in range(1,i+1):
    print("*", end = ' ')
  print('')
for x in range(n-1,0,-1):
  for y in range(x,0,-1):
    print("*", end =' ')
  print('')

# 3. Write a program to iterate a given list and count the occurrence of each element and create a dictionary to show the count of each element. 
# — sample_list = [11, 45, 8, 11, 23, 45, 23, 45, 89]
# —  Printing count of each item   {11: 2, 45: 3, 8: 1, 23: 2, 89: 1}

sample_list = [11, 45, 8, 11, 23, 45, 23, 45, 89]
count = 0
my_dictionary = {}
for i in sample_list:
  for j in range(0,len(sample_list)):
    if i == sample_list[j]:
      count +=1
    
  my_dictionary[i] = count
  count = 0
print(my_dictionary)

# 4. Remove special symbols from a string.

my_string = input()
new_string = ''
for i in my_string :
  if i.isalnum():
    new_string +=i
print(new_string)